# Generated by Django 3.1.3 on 2020-11-10 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parent',
            new_name='User',
        ),
    ]
