# Generated by Django 3.1.3 on 2020-11-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores_data', '0002_auto_20201110_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
