# Generated by Django 3.1.3 on 2020-11-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores_data', '0003_remove_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
